name: Auto-add Issues to Project Board

on:
  issues:
    types: [opened, reopened, transferred]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.6.0
        with:
          # CHANGE THIS: Replace YOUR_ORG and PROJECT_ID
          project-url: https://github.com/orgs/YOUR_ORG/projects/PROJECT_ID
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}